### PR TITLE
Example showing use of `JFX.pkgResourcesDir` setting to provide drop-in native packaging resources to jfx:deploy task

### PR DESCRIPTION
**Pull request by metasim**
I've done basic testing on this on MacOS X, so an iteration or two may be required before this is finalized. However I'm interested in feedback if you have time.

I don't have a Windows machine set up at the moment to test, so before merging might want to verify that this at least builds on Windows. I did add a custom application icon for windows packages so that something is in place to determine if the default icon is getting properly overridden.

Two areas to pay particular attention to when reviewing the build definition:
1. In `project/plugin-javafx.sbt` I'm using the SBT 0.13 form of git-based plugin referencing so that the `master` version of sbt-javafx is used.  I'm not expert enough with SBT to know how to do this in a cross-version manner. Obviously should be changed once 0.6 (or whatever) is released with `JFX.pkgResourcesDir` support.
2. In `example-packaging.sbt` the setting `JFX.devKit := JFX.jdk(System.getProperty("java.home") + "/..")` was required on my machine (MacOS X 10.9.1). I've needed to have this in other projects. Not sure if this is a bug in sbt-javafx finding the default path to `ant-javafx.jar`, or some configuration issue on my computers.

Something else I noted, which I'll try to debug further: When I run the final executable on MacOS, the application name is "fxApp" and not "example-packaging". As far as I can tell, the generated `build.xml` file is correct (passing through the `name` setting properly), so it may be a bug in the version of JavaFX I'm using (a few builds behind). However, the fact that the value of `refid="fxApp"` is showing up as the application runtime name is suspicions. I'd be interested in knowing if it's correct under Windows.

### CODE REVIEW

**Comment by kavedaa** [comment]
Thanks for your work.

I've tested your example on Windows, and the icon shows up as expected in the generated bundle. I'm not getting any verbose output about it though, not sure why.

You are correct in that the JFX.devKit setting is required for finding the ant-javafx.jar file. I'll consider adding a default fallback for this based on JAVA_HOME.

On Windows, the the final executable is named "example-packaging.exe", as expected. If the behaviour you are seeing is a bug (or intended) in the JavaFX packaging code such that the value of "refid" instead of the value of "name" is used as the name of the executable, we could work around it by setting "id" and "refid" fields to the name of the project (which might be a good idea anyway).

Two questions, from the perspective of wanting to keep the examples as simple as possible for users:

Is the specific SBT version (0.13.1) critical? (I would assume not.)

Is there any specific reason for placing the "package" directory inside the "project" directory?

**Comment by metasim** [comment]
> I'm not getting any verbose output about it though, not sure why.

As best I can tell, the only way you get the verbose output is if you run Ant outside of SBT. It doesn't appear that any console output from Ant while called by the sbt-javafx plugin gets redirected to the SBT console. In some ways this is a good thing since Ant is so verbose. (The fact that the ant-javafx tasks communicate configuration options in this manner seems brain dead to me anyway.) Not sure what options are available to the plugin via the Ant API, or even what the right approach is, but bypassing SBT at the moment seems to be the only way to see the verbose output.

> You are correct in that the JFX.devKit setting is required for finding the ant-javafx.jar file. I'll consider adding a default fallback for this based on JAVA_HOME.

I think having a default is a really good idea. The easier it works "out-of-the-box" the better.

> On Windows, the the final executable is named "example-packaging.exe", as expected. If the behaviour you are seeing is a bug (or intended) in the JavaFX packaging code such that the value of "refid" instead of the value of "name" is used as the name of the executable, we could work around it by setting "id" and "refid" fields to the name of the project (which might be a good idea anyway).

The executable name is correct on MacOS as well, the issue is with the runtime "process name"... or whatever it's called; the name that shows up in the menu bar and in the Activity Monitor (see images below). Not sure if Windows has a similar thing, but just wanted to point it out in case something came to mind for you.

> Is the specific SBT version (0.13.1) critical? (I would assume not.)

Only while the example needs to compile against the source version of sbt-javafx. Once an updated release on Maven Central is available with the `pkgResourcesDir` settings, the dependency can be removed once the plugin reference has been updated.

I just tried to compile a fresh package and something's amiss with the source version anyway.... looks like jfxrt.jar isn't getting added to the compiler class path. I'll follow up if I figure it out.

> Is there any specific reason for placing the "package" directory inside the "project" directory?

No. An arbitrary decision on my part. Could be `baseDirectory` or `src/main/resources` or whatever. Do whatever feels natural to you.

### Process Name on MacOS X

screen shot 2014-01-05 at 7 07 31 pm

screen shot 2014-01-05 at 7 10 47 pm

**Comment by metasim** [comment]
> I just tried to compile a fresh package and something's amiss with the source version anyway.... looks like jfxrt.jar isn't getting added to the compiler class path. I'll follow up if I figure it out.

Issue is that `JFX.addJfxrtToClasspath := true` is missing in the build file. Not sure how that slipped by. I'll create a change set for it.

**Comment by metasim** [comment]
With respect to:

> Is the specific SBT version (0.13.1) critical? (I would assume not.)

The code that requires 0.13.x is in `project/plugin-javafx.sbt`:

``` scala
lazy val root = project.in( file(".") ).dependsOn(sbtJavaFX)

lazy val sbtJavaFX = uri("https://github.com/kavedaa/sbt-javafx.git")
```

From the best I can tell, backwards compatibility with 0.12.x requires the creation of `project/project/Build.scala` with something like this:

``` scala
import sbt._
object PluginDef extends Build {
   override lazy val projects = Seq(root)
   lazy val root = Project("plugins", file(".")) dependsOn( sbtJavaFX )
   lazy val sbtJavaFX = uri("https://github.com/kavedaa/sbt-javafx.git")
}
```

(See: http://www.scala-sbt.org/0.12.4/docs/Extending/Plugins.html#d-project-dependency)

Would you rather this approach, or is waiting for the 0.6 OK?

**Comment by kavedaa** [comment]
> As best I can tell, the only way you get the verbose output is if you
> run Ant outside of SBT. It doesn't appear that any console output to Ant
> through by SBT through the sbt-javafx plugin gets redirected to the SBT
> console. In some ways this is a good thing since Ant is so verbose. The
> fact that the ant-javafx tasks communicate configuration options in this
> manner seems brain dead to me anyway. Not sure what options are
> available to the plugin via the Ant API, or even what the right approach
> is, but bypassing SBT at the moment seems to be the only way to see the
> verbose output.

That's odd. I'm quite sure I saw some verbose output inside SBT earlier 
when I added that setting. It doesn't seem to be an SBT version thing 
either. I can't see any good reason why it's not being redirected to 
SBT, as simple "println"'s from within the plugin are. The question is 
whether this is caused by Ant or by SBT. Most users probably won't use 
Ant standalone (or even have it installed, I don't), so we shouldn't 
rely to much on verbose output being available if we can't get SBT to 
show it.

> I think having a default is a really good idea. The easier it works
> "out-of-the-box" the better.

Sure, will add that.

> The executable name is correct on MacOS as well, the issue is with the
> runtime "process name"... or whatever it's called; the name that shows
> up in the menu bar and in the Activity Monitor (see images below). Not
> sure if Windows has a similar thing, but just wanted to point it out in
> case something came to mind for you.

I see. It seems from 6.3.5.1 of the JavaFX deployment docs that the id 
field in fx:application is used for this? That would explain what you're 
seeing, and if so we should use the application name here.

> Only while the example needs to compile against the source version of
> sbt-javafx. Once an updated release on Maven Central is available with
> the |pkgResourcesDir| settings, the dependency can be removed once the
> plugin reference has been updated.

Ok, fine.

> No. An arbitrary decision on my part. Could be |baseDirectory| or
> |src/main/resources| or whatever. Do whatever feels natural to you.

I'm not quite sure what would be the best practice here. Either at root 
level, or under src/something... have to think about it. :)

**Comment by kavedaa** [comment]
> Would you rather this approach, or is waiting for the 0.6 OK?

No, it's fine, we can just remove it once 0.6 is published.

**Comment by kavedaa** [comment]
> ```
> Is there any specific reason for placing the "package" directory
> inside the "project" directory?
> ```
> 
> No. An arbitrary decision on my part. Could be |baseDirectory| or
> |src/main/resources| or whatever. Do whatever feels natural to you.

The Gradle JavaFX plugin seems to use src/deploy/package. Perhaps we 
should do the same and also let it be the default?

http://jaxenter.com/tutorial-a-guide-to-the-gradle-javafx-plugin-46270.html

**Comment by metasim** [comment]
+1 for following another's lead. I'll update the example when I get through my current coding dash. Feel free to assign an issue to me if you'd like.

**Pull request merged**
